### ISSUE TITLE
fail to install prettierd for `No available formula with the name "prettierd". Did you mean prettier?`

### ISSUE THREAD

**Issue by damingerdai** [craftzdog/dotfiles-public#126]
i want to install prettierd with homtbrew

```bash
brew install prettierd
```

but fail:

```
Warning: No available formula with the name "prettierd". Did you mean prettier?
==> Searching for similarly named formulae and casks...
==> Formulae
prettier

To install prettier, run:
  brew install prettier

==> Casks
pretzel

To install pretzel, run:
  brew install --cask pretzel
```

i try to search the prettierd by googlde and found this one [fsouza/prettierd](https://github.com/fsouza/prettierd)

in this repo, it say that we can install this library

```bash
brew install fsouza/prettierd/prettierd
```

my question is that that two library are the same?

**Comment by damingerdai** [comment]
due to this [null-ls nvim](https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#prettierd). 

`brew install prettierd` is wrong...

please update [My Neovim setup for React, TypeScript, Tailwind CSS, etc](https://dev.to/craftzdog/my-neovim-setup-for-react-typescript-tailwind-css-etc-58fb)

**Comment by cattynip** [comment]
Well, basically, for my development environment, I had to install that package globally so that null-ls(none-ls currently) could run the package.

If you are using yarn,
```bash
yarn global add prettierd
```

If you are using npm,
```bash
npm install prettierd -g
```

If the problem is not still solved, decide to use other packages, including `eslint_d,` because I had a kind of bad experience with them.

Lastly, I could install `prettierd` with my brew. [This](https://formulae.brew.sh/formula/prettierd#default) is the brew link that shows the information about prettierd.
