### ISSUE TITLE
Dotfiles didn't apply

### ISSUE THREAD

**Issue by sabond9** [craftzdog/dotfiles-public#151]
Hi,

I setup terminal and shell with tools from your guide. I'm using mac os and Iterm2 and your dotfiles . But I didin't get the same result as you had on your videos: 

1. I had only ? icons
2. different colors from yours 
3. git bar is different from yours 
4. ctrl-r and ctrl didn't work

For detalis please check the picture below
![image](https://github.com/craftzdog/dotfiles-public/assets/22496695/e1b9cc07-05b8-43c0-a73e-8ab303cdc604)

**Comment by CofCat456** [comment]
1. use nerd font (he use [this](https://github.com/yuru7/PlemolJP))
3. use nerd font and run tide configure
4. If you want to use his settings, you must create the same file path as his (ex. Developments folder)

**Comment by PowerzinBR** [comment]
also, answering CofCat456, make sure you're using a recent fish version.

**Comment by iafshinafshin** [comment]
Hello
### step 1 
You must download your favorite [nerd font](https://nerdfonts.com/font-downloads) for shows icon.

### step 2
You must install 'fzf' plugin with fisher like this `fisher install PatrickF1/fzf.fish` and install fzf in your system, if your system is debian or ubuntu install with this codes ` git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf` and run this script in your terminal ` ~/.fzf/install` or install this simple code `sudo apt install fzf` and if your system is arch linux you can download with this code `sudo pacman -S fzf` install 

### step 3

remove **Developments from line 17 in fzf_change_directory.fish**

# The end
you must read README.md in this repositorie

**Comment by cattynip** [comment]
# This is long. But be patient and read it carefully, please.


## 1. I had only ? icons

You have to install [Nerd Font](https://www.nerdfonts.com/font-downloads) to activate the icons because the icons are parts of every single Nerd Font. If you want to use another font and still want to see the icons, then you will have to go to the iterm2 settings(Command+), enter the `Text` section, and hit some buttons like the image below.

<img width="575" alt="Screenshot 2024-01-29 at 01 42 42" src="https://github.com/craftzdog/dotfiles-public/assets/96553411/e4a4aa78-3dd2-4e94-857f-034ab707a1d9">

In the case of me, I wanted to use Fira Font but wanted to see the icons. I just hit the button `Use a different font for non-ASCII text` and put Hack Nerd Font, which is one of the nerd fonts available on the website provided and also what he used a long time ago.

PS I just found the Fira Nerd Font!

<img width="570" alt="Screenshot 2024-01-29 at 01 46 51" src="https://github.com/craftzdog/dotfiles-public/assets/96553411/e20496c5-9483-47c9-82d9-45af1d1edb16">

If you can successfully find the Nerd Font, you can disable all buttons and just put the font like the image provided above.

## 2. different colours from yours

Of course, you will see different colours than his because he adjusts the background colour value so that the background can be a little darker. I found him doing this on a YouTube video that I cannot remember, but anyway.

https://github.com/craftzdog/dotfiles-public/assets/96553411/5c830ae3-443c-43eb-b044-8d4fe8d782f9

On the video that I recorded, it shows how to make the background colours darker. In the same way, you can manually adjust every single colour in the way that you want it to look and expert the adjusted colour presets so that you can share it with others. Additionally, you can also import it from others. The exported/imported file used to have the extension `.itermcolors` and be written in XML.

Not only that, if you want your window to look exactly the same as his, then you may want to change the `transparency` and `blurriness` values inside of the `window` section. On the video provided below, it shows how to adjust those values.

https://github.com/craftzdog/dotfiles-public/assets/96553411/084bc619-e811-4ab1-bfe7-18b63c157be9

## 3. git bar is different from yours

I am not really sure about what you tried to say `git bar`, but I will assume that you saw the first image. What he uses to change his fish shell is Tide. I love it, too. You can install by typing `fisher install IlanCosman/tide@v6` *DO NOT FORGET TO RUN ANY `FISHER` COMMANDS AFTER YOU OPEN THE FISH SHELL*. And to configure that, you can simply run `tide configure`.

## 4. ctrl-r and ctrl didn't work

I do not use `fzf` thing at all. I am so sorry for not being helpful. These links below may help you.

- [fzf GitHub Link](https://github.com/junegunn/fzf)
- [fzf fish shell version GitHub Link](https://github.com/jethrokuan/fzf)
- [fzf fish shell version from different author GitHub Link](https://github.com/PatrickF1/fzf.fish)

---

Thank you for reading! 😄 I hope this helps you a lot in terms of understanding how to use fish shells and also how fonts work. If you have any questions, do not hesitate to ask me.

**Comment by zaaahir** [comment]
@cattynip Could you export your entire iTerm profile as a JSON rather than just the colours?

**Comment by cattynip** [comment]
@zaaahir Of course we can! That is what `profile` in iTerm is for. Profile basically saves all information for each section that you can see in the `Profile` tab. In the image below, there are tabs like `General`, `Colours`, and `Text`, right? All of the values of those sections are profile information. It includes simple information about colours, windows, and fonts to advanced information like sessions and notifications. So, if you change the profile and see the values there, you will be able to notice that the values for the current profile will change, but the values for the other profile won't.

<img width="1028" alt="Screenshot 2024-01-29 at 04 30 11" src="https://github.com/craftzdog/dotfiles-public/assets/96553411/6c67e7b6-7274-44d0-82f1-03a2fb297322">

And that also means iTerm should be able to provide us with the features of importing/exporting this session feature.

<img width="1050" alt="Screenshot 2024-01-29 at 04 34 39" src="https://github.com/craftzdog/dotfiles-public/assets/96553411/c58c8868-9371-41e5-95af-fb7cd2964f85">

In the image above, you can see the popup menu on the button `More Actions...`. It basically allows you to do a couple of actions for the selected profile. In this case, the profile `cattynip`, which is my nickname, is the selected profile. As you can guess, you can click on the `Save Profile as JSON...` to save all of the information of the selected profile but in a JSON file. Once you save your profile in JSON, you will be able to import that JSON file to add your profile, regardless of device!

Thank you for reading this long text. I hope this can help you and you use this feature a lot, @zaaahir. Again, do not hesitate to ask me if you have any questions.

**Comment by zaaahir** [comment]
@cattynip I was asking for your specific iTerm config, since it looks quite nice.

**Comment by cattynip** [comment]
Oh, mine?

**Comment by cattynip** [comment]
Tada- https://github.com/cattynip/dotfiles/blob/master/iterm/cattynip.json

**Comment by zaaahir** [comment]
Thank you!
