### ISSUE TITLE
Add your packer config

### ISSUE THREAD

**Issue by iafshinafshin** [craftzdog/dotfiles-public#153]
Hello, **you can create a branch in dotfiles for packer.nvim config with lua language**

**Comment by PowerzinBR** [comment]
Takuya can't, because Lazyvim is powered by **lazy.nvim, created by folke.**
If you wish to use **vim-plug use WayBack Machine (archive.org), archive recorded the previous configuration.** Thanks!
![image](https://github.com/craftzdog/dotfiles-public/assets/140966320/f3628804-2c21-4789-a76a-3822e92c1064)

**Comment by PowerzinBR** [comment]
Sorry, i didn't now  about this Github feature:
Look for a commit with the packer.nvim version

**Comment by iafshinafshin** [comment]
Hello,
yes but I very long time found that feature but after created this issues
