### ISSUE TITLE
This is important, @craftzdog

### ISSUE THREAD

**Issue by PowerzinBR** [craftzdog/dotfiles-public#156]
# Hello, Takuya!
Recently i found a channel named Bek Brace Plus, he/she got too much inspiration using even the character of a dog in ther videos, not exactly the same but he pratically copyed your video, let's say that.

And what video? Yes, setup of Windows Powershell
It's inspired i guess but he didn't put any credits on description and copyed even chapter names like
"Add a utility command - `whereis`"

I don't think thats fair because if he even credit you he used the same chapter name, same character (dog) and same expressions (like the tongue in the mouth, of the dog)

And also the core ingredient of your channel, the bubbles chat.

By the way, i am not american, i am from Brazil, so if my english is bad i'm so sorry!
Here goes the link for the video: https://www.youtube.com/watch?v=1iGlXYu87zc

@craftzdog

**Comment by PowerzinBR** [comment]
Please note, i don't want to give him hate, i think it's just too much inspired and without givin proper credits to Takuya.

**Comment by cattynip** [comment]
I am not Takuya, but I PERFECTLY 110% AGREE with you.

In the case of the bubble chat, that is okay because he has encouraged the viewers to use it on his video, and he even re-tweeted a guy who used the bubble chat thing on his blog video, which is good and is what Open Source is for, right?

But the problem is I have seen not only `Bek Brace Plus` but also too many YouTubers and people using exactly the same format or style of the videos as Takuya. And I have been worried about him because they did not even credit him, as you mentioned earlier. Those styles and techniques are what he has invented himself uniquely, which is admirable and should not be copied by somebody.

Well, I also wanted to mention it to Takuya directly and actually want him to process something on it because I love his content, and I know how his channel grew, having been watching his videos for over five years. So, every time somebody copied his things, I got mad at them, not being able to understand why they copied and did not give any credit even though I am not Takuya.

Anyway, this is my personal thoughts on it. And, @craftzdog, please comment or write a blog regarding this problem.

**Comment by PowerzinBR** [comment]
Oh thanks @cattynip, i sorry i made that mistake haha! But thanks for sending an answer if i was wrong!
This is awful because i think Takuya can't take care of ALL videos. Because he has a personal life. He is busy and try to always improve so he might be tired to take care of all this video and he just leave it.

However it's important to give credits to him because the same person previously used the same prompt of him, before he publish that video, people can get confused and even think a big channel copyed a small channel.

And how you say, this is OUR personal thoughts on it and we hope Takuya can handle this, because this is TOO much inspired, inspiring is okay, with permission.
But copying even the character and **chapter names?**

**Comment by PowerzinBR** [comment]
![image](https://github.com/craftzdog/dotfiles-public/assets/140966320/30670077-c457-4f5b-9067-961417551196)
![image](https://github.com/craftzdog/dotfiles-public/assets/140966320/8ba74b1d-ddf5-4e1f-91a1-f3761e88d708)

**Comment by cattynip** [comment]
Oh, @PowerzinBR, I watched the video before, and I just looked for details of the video. I just saw the comments, section, and even character... bro, it is... very serious. 

I looked up the descriptions; I found these pieces of information if you want.

His GitHub: https://github.com/BekBrace
The NeoVim Setting Repository: https://github.com/BekBrace/NeoVim-Settings
His Main YouTube Channel: https://www.youtube.com/bekbrace
His Blog: https://dev.to/bekbrace
His Official Website: https://bekbrace.netlify.app/

> I guess his website is too similar to the official website of Forrest Knight

`a little bit indeed`?

**Comment by PowerzinBR** [comment]
Yes, @cattynip it's serious because he says he got a little bit inspired? I didn't think copying the chapter names is a little bit inspired, and the character
Also, changing topic, do you have any social media we can talk better? Like Discord or something? Let's change the topic in another place, choose a repo from my profile and let's talk in the issue haha

**Comment by cattynip** [comment]
Wow, ok. https://instagram.com/cattynip.dev

**Comment by PowerzinBR** [comment]
Hm... don't have Instagram, but getting back in topic

I think this is not acceptable, Takuya needs to take an action about this.

**Comment by cattynip** [comment]
Well, I think what we can do is just wait for him to see this issue...

**Comment by PowerzinBR** [comment]
@craftzdog Hello, could you see this?

**Comment by craftzdog** [comment]
I've been seeing those copycats but let's forgive them unless it's illegal. Stealing is one of the great ways to learn.
